apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: groovy-print-job
spec:
  selector:         
    matchLabels:
      app: groovy
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: groovy
      labels:
        app: groovy
    spec:
      containers:
      - name: groovy
        image: 172.30.177.25:5000/groovy/fis-groovy-openshift@sha256:b9d95b3214d928a666e430e96cb016a867a34a31ca937133d4db4a1f468732e0
        command: ["groovy",  "-e", "\"println 'Hello World'\""]
      restartPolicy: Never
